org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft properties
minecraft_version = 1.20.1
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)


# Mod properties
mod_version = 1.0.0
mod_group_id = net.tessa.mcmtforge
mod_id = mcmtforge
mod_name = MCMTForge
minecraft_version_range=[1.20.1,1.20.4)
mod_license=All Rights Reserved
mod_authors=ppls (TODO: UPDATE ME)
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=a


#mapping
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
